[en]
pt= "pt"
pts= "pts"
points= "Points"
assignment= "Assignment"
total= "Total"
awarded= "Awarded"

[de]
pt= "pt"
pts= "pts"
points= "Punkte"
assignment= "Aufgabe"
total= "Gesamt"
awarded= "Erreicht"