class = "IAV12"
subject = "BSA"
authors = "jomaway"

[sa1]
title = "1.Schulaufgabe"
date = 2023-12-12
show_solution = true

[sa2]
title = "2.Schulaufgabe"
date = 2024-04-17
show_solution = false

[ka]
title = "Kurzarbeit"
date = 2024-01-28
show_solution = false