[[questions]]
type = "mct"
prompt.prompt = """
What does it mean if a variable `x` is immutable?
"""
prompt.distractors = [
  "`x` is stored in the immutable region of memory.",
  "After being defined, `x` can be changed at most once.",
  "You cannot create a reference to `x`."
]
answer.answer = "`x` cannot be changed after being assigned to a value."
context = """
Immutable means "not mutable", or not changeable.
"""

[[questions]]
type = "mct"
prompt.prompt = """
  Auf welcher Schicht arbeitet ein Router?
"""
prompt.distractors = [
  "Bitübertragungsschicht",
  "Anwendungsschicht",
  "Transportschicht"
]
answer.answer = "Netzwerkschicht"
context = "A router works with IP Adresses."
