[package]
name = "ttt-worksheet"
version = "0.1.0"
compiler = "0.11.0"
entrypoint = "lib.typ"
authors = ["Jomaway <https://github.com/jomaway>"]
license = "MIT"
description = "Part of the ttt-collection to make a teachers life easier." 
repository = "https://github.com/jomaway/typst-teacher-templates"
keywords = "worksheets, teacher, tutorial, teaching, education"
categories = ["components", "utility", "office"]
discipline = ["education"]

[template]
path = "template"
entrypoint = "worksheet.typ"
thumbnail = "thumbnail.png"