[en]
pt= "pt"
pts= "pts"
points= "Points"
assignment= "Assignment"
total= "Total"
awarded= "Awarded"
good_luck = "Good Luck"
grade = "Grade"
name = "Name"
class = "Class"
subject = "Subject"
date = "Date"

[de]
pt= "pt"
pts= "pts"
points= "Punkte"
assignment= "Aufgabe"
total= "Gesamt"
awarded= "Erreicht"
good_luck = "Viel Erfolg"
grade = "Note"
name = "Name"
class = "Klasse"
subject = "Fach"
date = "Datum"